% Options for packages loaded elsewhere
% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
\PassOptionsToPackage{dvipsnames,svgnames,x11names}{xcolor}
%
\documentclass[
  11pt,
]{article}
\usepackage{xcolor}
\usepackage[margin = 1in]{geometry}
\usepackage{amsmath,amssymb}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math} % this also loads fontspec
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
\usepackage{lmodern}
\ifPDFTeX\else
  % xetex/luatex font selection
  \setmainfont[]{Palatino}
  \setmathfont[]{STIX Two Math}
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\usepackage{setspace}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother


\usepackage{longtable,booktabs,array}
\usepackage{calc} % for calculating minipage widths
% Correct order of tables after \paragraph or \subparagraph
\usepackage{etoolbox}
\makeatletter
\patchcmd\longtable{\par}{\if@noskipsec\mbox{}\fi\par}{}{}
\makeatother
% Allow footnotes in longtable head/foot
\IfFileExists{footnotehyper.sty}{\usepackage{footnotehyper}}{\usepackage{footnote}}
\makesavenoteenv{longtable}
\usepackage{graphicx}
\makeatletter
\newsavebox\pandoc@box
\newcommand*\pandocbounded[1]{% scales image to fit in text height/width
  \sbox\pandoc@box{#1}%
  \Gscale@div\@tempa{\textheight}{\dimexpr\ht\pandoc@box+\dp\pandoc@box\relax}%
  \Gscale@div\@tempb{\linewidth}{\wd\pandoc@box}%
  \ifdim\@tempb\p@<\@tempa\p@\let\@tempa\@tempb\fi% select the smaller of both
  \ifdim\@tempa\p@<\p@\scalebox{\@tempa}{\usebox\pandoc@box}%
  \else\usebox{\pandoc@box}%
  \fi%
}
% Set default figure placement to htbp
\def\fps@figure{htbp}
\makeatother


% definitions for citeproc citations
\NewDocumentCommand\citeproctext{}{}
\NewDocumentCommand\citeproc{mm}{%
  \begingroup\def\citeproctext{#2}\cite{#1}\endgroup}
\makeatletter
 % allow citations to break across lines
 \let\@cite@ofmt\@firstofone
 % avoid brackets around text for \cite:
 \def\@biblabel#1{}
 \def\@cite#1#2{{#1\if@tempswa , #2\fi}}
\makeatother
\newlength{\cslhangindent}
\setlength{\cslhangindent}{1.5em}
\newlength{\csllabelwidth}
\setlength{\csllabelwidth}{3em}
\newenvironment{CSLReferences}[2] % #1 hanging-indent, #2 entry-spacing
 {\begin{list}{}{%
  \setlength{\itemindent}{0pt}
  \setlength{\leftmargin}{0pt}
  \setlength{\parsep}{0pt}
  % turn on hanging indent if param 1 is 1
  \ifodd #1
   \setlength{\leftmargin}{\cslhangindent}
   \setlength{\itemindent}{-1\cslhangindent}
  \fi
  % set entry spacing
  \setlength{\itemsep}{#2\baselineskip}}}
 {\end{list}}
\usepackage{calc}
\newcommand{\CSLBlock}[1]{\hfill\break\parbox[t]{\linewidth}{\strut\ignorespaces#1\strut}}
\newcommand{\CSLLeftMargin}[1]{\parbox[t]{\csllabelwidth}{\strut#1\strut}}
\newcommand{\CSLRightInline}[1]{\parbox[t]{\linewidth - \csllabelwidth}{\strut#1\strut}}
\newcommand{\CSLIndent}[1]{\hspace{\cslhangindent}#1}



\setlength{\emergencystretch}{3em} % prevent overfull lines

\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}



 


%%% Setup for frontmatter, spacing, and colors %%%

\usepackage{orcidlink} % for Orchid ID

% set the geometry of the document
\usepackage{indentfirst} % indent first para
\setlength{\parindent}{0.5in} % set indent length
\setlength{\parskip}{0em} % no extra space between paras

% set spacing of section titles
\usepackage{titlesec} % to set spacing of section titles
\titlespacing\section{0pt}{0pt plus 2pt minus 2pt}{0pt plus 2pt minus 2pt}
\titlespacing\subsection{0pt}{0pt plus 2pt minus 2pt}{0pt plus 2pt minus 2pt}
\titlespacing\subsubsection{0pt}{0pt plus 2pt minus 2pt}{0pt plus 2pt minus 2pt}

%%% Figures and Tables %%%

% captions 
\usepackage{caption}
\captionsetup{
  %captionskip = 0pt,   % eliminate space bw capiton and figure
  %font = bf,            % make the font of the entire caption bold
  %font = footnotesize,         % make font of entire caption smaller
  justification = raggedright, % left justify the caption 
  singlelinecheck = true,      % but only if it is more than one line
  labelfont = bf               % make the caption label bold
}
\setlength{\abovecaptionskip}{10pt} % Adjust the space above the caption

% for rotating figures and tables
\usepackage{rotating}        
\usepackage{pdflscape}

%%% Abstract %%%

\usepackage{abstract}
\renewcommand{\abstractname}{ABSTRACT\vspace{.5em}}
\renewcommand{\abstractnamefont}{\normalfont\bfseries}
\renewcommand{\abstracttextfont}{\normalsize}
\setlength{\absleftindent}{\parindent}
\setlength{\absrightindent}{\parindent}

%% Title %%%

\usepackage{titling}
%\setlength{\droptitle}{3em}
\pretitle{\par\vskip 3em\begin{center}\LARGE\bfseries}
\posttitle{\par\end{center}\vspace{2\baselineskip}}

%%% New commands %%%

% Keywords
\providecommand{\keywords}[1]{\textbf{\textit{Keywords---}}#1}

% Keywords
\providecommand{\fundinginfo}[1]{\textbf{\textit{Funding: }}#1}

% Word count
\providecommand{\wordcount}[1]{\textbf{Word Count: }#1}

% Conflicts
\providecommand{\conflicts}[1]{\textbf{\textit{Conflicts of Interest: }}#1}

% Command for a note at the top of the first page describing the publication
% status of the paper.
\newcommand{\published}[1]{%
   \gdef\puB{#1}}
   \newcommand{\puB}{}
   \renewcommand{\maketitlehooka}{%
       \par\noindent\footnotesize\sffamily\puB}
\usepackage{booktabs}
\usepackage{caption}
\usepackage{longtable}
\usepackage{colortbl}
\usepackage{array}
\usepackage{anyfontsize}
\usepackage{multirow}
\makeatletter
\@ifpackageloaded{caption}{}{\usepackage{caption}}
\AtBeginDocument{%
\ifdefined\contentsname
  \renewcommand*\contentsname{Table of contents}
\else
  \newcommand\contentsname{Table of contents}
\fi
\ifdefined\listfigurename
  \renewcommand*\listfigurename{List of Figures}
\else
  \newcommand\listfigurename{List of Figures}
\fi
\ifdefined\listtablename
  \renewcommand*\listtablename{List of Tables}
\else
  \newcommand\listtablename{List of Tables}
\fi
\ifdefined\figurename
  \renewcommand*\figurename{Figure}
\else
  \newcommand\figurename{Figure}
\fi
\ifdefined\tablename
  \renewcommand*\tablename{Table}
\else
  \newcommand\tablename{Table}
\fi
}
\@ifpackageloaded{float}{}{\usepackage{float}}
\floatstyle{ruled}
\@ifundefined{c@chapter}{\newfloat{codelisting}{h}{lop}}{\newfloat{codelisting}{h}{lop}[chapter]}
\floatname{codelisting}{Listing}
\newcommand*\listoflistings{\listof{codelisting}{List of Listings}}
\makeatother
\makeatletter
\makeatother
\makeatletter
\@ifpackageloaded{caption}{}{\usepackage{caption}}
\@ifpackageloaded{subcaption}{}{\usepackage{subcaption}}
\makeatother
\usepackage{bookmark}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same}
\hypersetup{
  pdftitle={Extracting Event Counts and Locations from Conflict Reports},
  pdfauthor={Emmanuel Teitelbaum},
  colorlinks=true,
  linkcolor={Blue4},
  filecolor={Maroon},
  citecolor={Blue4},
  urlcolor={Blue4},
  pdfcreator={LaTeX via pandoc}}


%% Main title %%

\title{Extracting Event Counts and Locations from Conflict
Reports\thanks{I am grateful to Mohiddin Bacha Shaik and Shiva Sharma
for their excellent research assitance.}}

%% Subtitle %%

\usepackage{etoolbox}
\makeatletter
\providecommand{\subtitle}[1]{% add subtitle to \maketitle
  \apptocmd{\@title}{\par {\vskip 0.25em \large #1 \par}}{}{}
}
\makeatother
\subtitle{Evidence from the South Asia Terrorism Portal}

%% Author info %%

  \author{Emmanuel Teitelbaum\thanks{Corresponding author.}
~\orcidlink{0000-0001-7089-0588}
\\George Washington University
\\Department of Political Science
\\\href{mailto:ejt@gwu.edu}{ejt@gwu.edu}
 }

% Omit the date since the \published command does that
\date{}  % blank date

\usepackage{url}
\urlstyle{same}
\begin{document}
%%% Title Section %%%

\newgeometry{top=0.5in, bottom=1in, left=1in, right=1in}

\published{\textbf{2026-04-08} \qquad Prepared for the APSA Virtual
Research Meeting. \\ {\scriptsize Access the code, data, and analysis at
\url{https://github.com/eteitelbaum/code-satp.git}}}

\vspace{0.25in}

\maketitle

\vspace{0.25in}

%%% Abstract %%%

\begin{abstract}
\noindent            %eliminate indent in abstract
This paper evaluates the performance of transformer models on the task
of extracting death counts from conflict event narratives. Using
hand-coded incident summaries from the South Asia Terrorism Portal on
the Maoist insurgency in India, I compare fine-tuned
sequence-to-sequence models and prompted large language models against a
ConfliBERT-Poisson baseline. The distribution of death counts in the
corpus is highly skewed, with most incidents concentrated in the lower
count values and relatively few observations in the upper tail. I
evaluate model performance using overall mean absolute error and a
bin-level framework spanning \texttt{0}, \texttt{1}, \texttt{2},
\texttt{3-5}, and \texttt{6+} deaths. The results show that generative
models outperform the encoder baseline on aggregate measures, but that
aggregate performance obscures weaker results on rare high-fatality
cases. Training-side interventions on Flan-T5-Large yield limited
improvement and do not close the gap on the highest fatality bin,
whereas prompt-based interventions substantially improve Llama-3.1-8B.
Few-shot prompting built around bin-balanced and hard-case examples
raises exact match on the \texttt{6+} bin from 78.9 percent to 89.5
percent, matching GPT-4o-mini. These findings indicate that automated
death count extraction can support conflict research and that its
evaluation should account for variation across the count distribution.
\end{abstract}

\vspace{\baselineskip}




\vspace{0.25in}

%%% Word Count %%%


\vspace{0.25in}

%%% Funding %%%

\noindent
\fundinginfo{This project received funding from the Smith Richardson
Foundation and in-kind support from the GW Institute for International
Economic Policy.}

%%% Conflicts %%%


\restoregeometry

\setstretch{1.5}
\section{Introduction}\label{introduction}

Automated conflict event coding has advanced substantially in recent
years. Transformer-based models now perform well on tasks such as
identifying actors, classifying event types, and recovering structured
information from conflict narratives (\citeproc{ref-hu2022}{Hu et al.
2022}; \citeproc{ref-halterman2021}{Halterman et al. 2021}). Yet the
extraction of fatality counts remains less well developed in the
automation literature despite its importance for conflict measurement.
Existing event datasets routinely record fatality counts, and automated
systems sometimes attempt to extract them, but count fields have
generally been treated as secondary outputs rather than as a research
problem in their own right. For example, GDELT's V2COUNTS field remains
widely used despite longstanding concerns about noise and validity
(\citeproc{ref-leetaru2013}{Leetaru and Schrodt 2013}), while more
recent work in the abstractive event extraction literature incorporates
fatality counts as one field among many rather than treating count
extraction as the primary object of analysis
(\citeproc{ref-simon2025}{Simon et al. 2025}). As a result, conflict
research now has a growing literature on automated coding of who acted,
where, and in what form, but much less evidence on how well current
models recover the fatality information used to measure conflict
severity.

Fatality counts represent a distinct measurement problem because their
distribution is highly skewed. In conflict event data, most observations
are concentrated at the lower end of the count distribution, while
high-fatality events are relatively uncommon. Under these conditions,
aggregate performance metrics may obscure systematic error in the upper
tail. This is consequential for conflict research because fatality
counts are used to characterize variation in conflict severity and
escalation. Recent evidence further suggests that naive large language
model prompting for conflict fatality counts can be unstable and
sensitive to query formulation, indicating a need for more systematic
evaluation (\citeproc{ref-steinert2025}{Steinert and Kazenwadel 2025}).

This paper examines death count extraction using roughly 10,000
hand-coded incident summaries from the South Asia Terrorism Portal on
the Maoist insurgency in India. I compare two modeling approaches. The
first uses fine-tuned sequence-to-sequence models, with Flan-T5-Large as
the primary model and T5-XL-QLoRA as an upper-bound comparison. The
second uses prompted large language models, with Llama-3.1-8B as the
primary model and GPT-4o-mini as a benchmark. Both are evaluated against
a ConfliBERT-Poisson baseline on the same held-out test set. The
analysis proceeds in three stages. It first establishes baseline
performance across model families. Next, it introduces a bin-level
evaluation framework spanning \texttt{0}, \texttt{1}, \texttt{2},
\texttt{3-5}, and \texttt{6+} deaths to identify where aggregate metrics
obscure performance differences. Finally, the paper tests a set of
targeted interventions designed to improve performance on rare
high-count cases.

The results show that generative models outperform the encoder baseline
on aggregate measures, while the bin-level analysis reveals sharper
differences on rare high-fatality cases. Few-shot prompting
substantially improves Llama-3.1-8B on the highest count bin, while
training-side interventions on Flan-T5-Large yield more limited gains.
The analysis indicates that automated extraction of count fields should
not be evaluated with aggregate error alone, since models that appear
broadly similar may differ substantially in the upper tail of the
distribution. It also suggests that automated death count extraction can
support conflict research, but that high-fatality cases remain the point
at which closer scrutiny is required.

\section{Count Extraction and the Rare-Event
Problem}\label{count-extraction-and-the-rare-event-problem}

Automated conflict event coding has made substantial progress on
classification tasks such as identifying event types, coding actor
dyads, and tagging locations. These tasks share a structure amenable to
standard supervised learning: they involve a fixed label set, outputs
that can be evaluated against a predefined ontology, and answers that
can often be recovered as text spans. In contrast, extracting counts
differs in several key ways that make it substantially harder. Consider
the following passage from the dataset of Maoist conflict events used
for this study:

\begin{quote}
Two CRPF personnel were killed and four others injured during an
encounter with cadres of the CPI-Maoist in Giridih District. The
encounter followed an ambush by the Maoists on a Police patrol in the
Madhuban forest area and it reportedly continued for over 12 hours.
Police sources claimed that over a dozen Maoists were killed, but their
colleagues managed to take away the bodies. Maoists also triggered seven
landmine blasts during the encounter.
\end{quote}

The passage does not yield a single unambiguous count. Two CRPF deaths
are explicitly confirmed while ``over a dozen Maoists'' are claimed
killed but their bodies were not recovered. A model, just like a human
coder, must decide whether unconfirmed, unrecovered deaths count, and if
so, how to interpret ``over a dozen'' as a point estimate. The answer
requires the model to attribute the outcome to a group, handle
uncertainty, and aggregate counts across clauses, before it even
encounters the competing numeric expressions ``four others injured'' and
``seven landmine blasts'' that it must discard. Meanwhile, the exclusion
of Maoist fatalities would require the model to record zero fatalities
for one actor (Maoists) while maintaining the total (two) for the other
actor (the police). Yet by including the Maoist fatalities the model
would need to produce a count in the high-fatality tail of the training
distribution which, as we show below, is the range where all models face
the greatest challenge.

We can summarize the main challenges as follows:

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  \emph{Unbounded output space.} The model must produce a non-negative
  integer over a potentially large range, including values that are rare
  or unseen in training;
\item
  \emph{Non-verbatim answers.} The correct count is often not a single
  text span, but must be constructed from information distributed across
  clauses or conditioned on qualifiers;
\item
  \emph{Zero discrimination.} Zero is a common and meaningful outcome
  even when numeric expressions are present, requiring the model to
  ignore irrelevant quantities (e.g., arrests, escapes, injuries);
\item
  \emph{Outcome and actor attribution.} The model must distinguish
  between different types of events (killed, wounded, arrested, escaped)
  and correctly assign counts to actor categories;
\item
  \emph{Uncertainty and ranges.} Reports frequently include ranges,
  qualified claims, or provisional outcomes, requiring the model to
  decide how to handle lower and upper bounds and whether to include
  uncertain or delayed information.
\end{enumerate}

A variety of approaches have been adopted for automated count
extraction, each facing identifiable limits with respect to the
challenges described above. Even the most capable generative models
struggle to produce accurate counts for rare, high-fatality events, and
no prior study has systematically examined whether targeted
interventions can address this failure.

\subsection{Approaches to Count
Extraction}\label{approaches-to-count-extraction}

Work on automated count extraction has progressed from early rule-based
systems that locate numeric tokens near death-related keywords, through
supervised encoder models trained on labeled examples, to the generative
neural architectures that now represent the state of the art. Where
earlier systems search for a number already present in the text,
generative models produce a predicted count by reasoning over the full
input. Recent work on structured event extraction from conflict reports
has converged on generative architectures as the most capable approach
for producing count outputs.

\subsubsection{Dictionary-Based
Approaches}\label{dictionary-based-approaches}

The earliest automated conflict coding systems relied on dictionary
matching, where keyword co-occurrences trigger event codes and proximity
to numeric tokens produces candidate counts
(\citeproc{ref-schrodt1994}{Schrodt and Gerner 1994}). For example,
GDELT's V2COUNTS field extracts counts by associating number tokens with
nearby death-related terms (\citeproc{ref-leetaru2013}{Leetaru and
Schrodt 2013}). Dictionary-based count fields are widely understood to
be unreliable. Overcounting is systematic because any number near a
death keyword becomes a count candidate, aggregation across clauses is
impossible, and zero cannot be represented because a zero-fatality event
does not produce a number to extract.

\subsubsection{Sequence-to-Sequence
Models}\label{sequence-to-sequence-models}

More recently, researchers have applied sequence-to-sequence models to
structured information extraction from text, including count fields in
conflict and crisis event datasets. Built on encoder-decoder
architectures such as T5 and its instruction-fine-tuned variants
(\citeproc{ref-chung2022}{Chung et al. 2022}), these models encode the
full input bidirectionally and generate outputs autoregressively.
Seq2seq models can aggregate partial counts, infer zero from the absence
of fatality evidence, and produce counts even when the text is indirect.
Simon et al. (\citeproc{ref-simon2025}{2025}) demonstrate this
capability on UCDP data, where fine-tuned generative models achieve
approximately 69\% exact match on the Deaths Low field.

The ceiling of seq2seq models is nonetheless bounded by arithmetic
reasoning capacity. For example, a model fine-tuned on sufficient
examples can learn that two soldiers and three militants sum to five,
but its ability to handle longer, multi-group casualty chains scales
with model size rather than training data volume. We should therefore
expect a gap between smaller and larger seq2seq models on high-count
cases that training-side interventions cannot easily close.

\subsubsection{Decoder-Only Large Language
Models}\label{decoder-only-large-language-models}

Decoder-only large language models (LLMs) such as Llama and GPT-4o-mini
offer a related but distinct approach to count extraction. These models
generate responses conditioned on a natural language prompt without any
encoding step. Decoder-only models bring two relevant capabilities. The
first is knowledge learned during large-scale pretraining that can
assist with context disambiguation. The second is in-context learning,
or the ability to adapt responses based on examples provided in the
prompt without updating its parameters (\citeproc{ref-brown2020}{Brown
et al. 2020}).

Recent work shows that LLMs can perform count extraction accurately when
counts are small, explicitly stated, and the distribution is not heavily
skewed (\citeproc{ref-braun2025}{Braun and Oswald 2025}). In practice,
however, Steinert and Kazenwadel (\citeproc{ref-steinert2025}{2025})
shows how naive zero-shot prompting for conflict fatality counts can be
unreliable and sensitive to how the question is framed, with estimates
shifting with language choice in ways that do not track actual event
severity. This suggests that LLM count extraction is not simply a matter
of asking the right question but requires examples that demonstrate the
full range of the target distribution, including the high-fatality tail
that naive prompting systematically underrepresents.

\subsubsection{Encoder Models with a Regression
Head}\label{encoder-models-with-a-regression-head}

Another interesting avenue adapts pretrained encoder models for count
prediction by appending a regression head to the encoder's text
representation, producing a predicted count directly rather than
generating it token by token.\footnote{The extractive alternative treats
  count extraction as a span-selection problem, identifying a numeric
  token in the text as the answer, but this fails because the correct
  count is frequently not a verbatim span and may require aggregation
  across clauses or a zero output when no deaths are mentioned.} Zhong,
Dhuliawala, and Stoehr (\citeproc{ref-zhong2023}{2023}) apply this
approach to victim count extraction for crisis events using a
numeracy-augmented encoder, providing the closest prior precedent for
conflict fatality prediction. While encoder models with regression heads
have not been applied to conflict event coding, they can provide a
useful architectural baseline against which to evaluate generative
models.

\subsection{Evaluation Gaps and Targeted
Interventions}\label{evaluation-gaps-and-targeted-interventions}

The approaches described above have been evaluated in isolation, on
datasets with different distributional properties, and using aggregate
metrics that obscure performance on rare high-count events. Simon et al.
(\citeproc{ref-simon2025}{2025}) report an aggregate ``deaths score'' as
the mean across six sub-fields, Zhong, Dhuliawala, and Stoehr
(\citeproc{ref-zhong2023}{2023}) evaluate overall extraction performance
without breaking out results by count magnitude, and Semnani et al.
(\citeproc{ref-semnani2025}{2025}) report aggregate event extraction F1
that conflates count fields with categorical and boolean variables. No
prior study systematically compares approaches on the same data, applies
interventions targeting rare-count failure, or reports bin-level
performance designed to expose systematic failure at the high end of the
distribution.

The most recent work frames count extraction as one component of a
broader abstractive event extraction agenda
(\citeproc{ref-simon2025}{Simon et al. 2025};
\citeproc{ref-semnani2025}{Semnani et al. 2025}). These studies are
oriented toward demonstrating system capabilities across multiple event
fields simultaneously rather than optimizing performance on any single
field or investigating the effect of targeted interventions. They
establish that generative models can extract count information from
conflict text but leave open the question of whether performance on rare
high-count events can be meaningfully improved and at what cost.

This gap matters because conflict fatality distributions are heavily
right-skewed, with most events recording zero or very few deaths and a
small minority recording mass casualties. Standard evaluation metrics
such as mean absolute error or root mean squared error are dominated by
common low-count cases and can mask systematic failure at the high end.
High-fatality events drive conflict severity indices, escalation
assessments, and policy responses, and errors on rare but extreme cases
are not marginal (\citeproc{ref-eck2012}{Eck 2012}). A model that
performs well on zero and single-fatality events while failing
consistently on events with ten or more deaths would appear competitive
under standard evaluation but be inadequate for the cases that matter
most for conflict measurement.

Two classes of intervention are available to address this. For seq2seq
models, training-side strategies address the data imbalance directly by
augmenting training examples through back-translation
(\citeproc{ref-sennrich2016}{Sennrich, Haddow, and Birch 2016}),
oversampling rare-count events, or applying loss functions that penalize
high-count errors more heavily. These interventions increase the model's
exposure to hard cases but cannot compensate for architectural capacity
constraints. For decoder LLMs, the analogous intervention is prompt
engineering, specifically providing few-shot examples that demonstrate
the full range of the output distribution. Theory predicts that examples
are more effective than additional instructions because examples
directly anchor the model to the output distribution rather than
describing it abstractly (\citeproc{ref-brown2020}{Brown et al. 2020};
\citeproc{ref-wei2023}{Wei et al. 2023}). We test both classes of
intervention systematically below.

\section{Data and Coding Protocol}\label{data-and-coding-protocol}

The interventions described above are evaluated on incident reports from
the South Asia Terrorism Portal (SATP), a publicly accessible repository
of conflict event summaries for South Asia.\footnote{South Asia
  Terrorism Portal, Institute for Conflict Management (www.satp.org).} I
use incidents covering the Maoist (Naxalite) insurgency in India from
2005 to 2016, a period that captures the peak intensity of the conflict
across central and eastern India. The full corpus contains approximately
9,919 incident reports involving security forces (CRPF, STF, CoBRA, and
state police), CPI-Maoist cadres, and civilians.

The SATP corpus has been used extensively in both the conflict studies
and NLP literatures, making it a well-validated foundation for this
study's experiments. Moreover, a single-conflict corpus offers
diagnostic advantages over multi-conflict datasets. In datasets covering
many conflicts, a model error on a count field could stem from multiple
causes that are difficult to disentangle, such as actor
misidentification, inconsistent reporting conventions across conflicts,
variation in source languages, or failures in count extraction itself.
In the SATP corpus, actor identification is fixed across every incident,
the language is consistently English, and the reporting conventions are
drawn from a single source. When a model underpredicts a high-fatality
incident, we can rule out these alternative explanations and attribute
the failure specifically to how the model handles uncertainty in the
source text.

In order to focus the analysis on incidents where fatality counts are
relevant, I filtered the dataset to armed assault and bombing events,
thereby excluding non-violent events such as surrenders, arrests, and
abductions. This yielded a working corpus of approximately 4,300
incidents. Despite restricting to violent event types, the distribution
of death counts remains highly skewed (see Figure~\ref{fig-bin-dist}).

\begin{figure}

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{satp-counts_files/figure-pdf/fig-bin-dist-1.pdf}}

}

\caption{\label{fig-bin-dist}Distribution of death counts in the
filtered SATP corpus (armed assault and bombing events, 2005--2016).
Thirty-seven percent of incidents record zero deaths and 75\% record
zero or one, while only 4.4\% fall in the 6+ bin.}

\end{figure}%

Thirty-seven percent of incidents record zero deaths, 38\% record
exactly one, 12\% record two, 9\% fall in the three-to-five range, and
only 4.4\% record six or more fatalities. This skewed distribution poses
a fundamental challenge for automated extraction because models trained
on data where 75\% of incidents record zero or one death have little
basis for accurately predicting the rare but consequential high-count
events.

The dataset records a fatality count for each incident following the
SATP source material, coding all deaths mentioned in the incident report
as well as a breakdown by actor category.\footnote{This paper does not
  analyze the breakdown of fatalities by actor group (security forces,
  Maoist cadres, and civilians) but the per-side decomposition is a
  natural extension of this work.} This straightforward approach belies
deeper epistemological questions related to the quality and veracity of
conflict reportage. Some reported deaths are confirmed by physical
evidence and independent sources, while others rest on unverifiable
claims by one party to the conflict. Major conflict datasets feature
different approaches to addressing such nuances. UCDP applies a
conservative lower-bound standard, discounting single-source claims of
combatant deaths (\citeproc{ref-sundberg2013}{Sundberg and Melander
2013}), whereas ACLED records deaths as reported and codes the source
separately, leaving the evidentiary judgment to the user
(\citeproc{ref-raleigh2010}{Raleigh et al. 2010}). The coding in this
study is closer to the ACLED approach, recording what the source
documents report without applying an independent evidentiary filter.

For model training, I split the filtered corpus into training,
validation, and test sets using a stratified random split that preserves
the count bin distribution across all three partitions. The training set
is comprised of approximately 2,580 incidents (60\%), and the validation
and test sets each consist of 859 incidents (20\% each). The test set
was held out throughout all model development, while the validation set
was used to monitor training loss and implement early stopping for the
seq2seq models and to evaluate the few-shot prompt interventions prior
to final testing.

\section{Models and Evaluation
Framework}\label{models-and-evaluation-framework}

To evaluate model performance across the full range of the count
distribution, I implement a two-track experimental design. The first
track fine-tunes a family of seq2seq models directly on the SATP
training data. The second evaluates instruction-tuned large language
models through prompt engineering, without updating model parameters.
Both tracks are evaluated on the same held-out test set and assessed
against a shared encoder baseline that combines a conflict-domain
pretrained model with a Poisson regression head. The evaluation combines
aggregate metrics with a bin-level decomposition across five count bins
(0, 1, 2, 3--5, and 6+) to assess performance on rare high-fatality
events.

\subsection{Seq2seq Models}\label{seq2seq-models}

I evaluate six seq2seq models plus a ceiling reference, all available
via the HuggingFace Model Hub. Each incident summary is formatted as a
question-answering input with the prompt ``How many people were killed?
Answer with only a number.'' prepended to the text.

\begin{itemize}
\tightlist
\item
  \emph{Flan-T5-Large} (\citeproc{ref-chung2022}{Chung et al. 2022}): A
  770M parameter encoder-decoder model instruction fine-tuned on a
  mixture of supervised tasks. This is the primary model in the seq2seq
  track.
\item
  \emph{T5-Base} and \emph{T5-Large} (\citeproc{ref-raffel2020}{Raffel
  et al. 2020}): Standard encoder-decoder comparators at 220M and 770M
  parameters respectively.
\item
  \emph{IndicBART} (\citeproc{ref-dabre2022}{Dabre et al. 2022}): An
  encoder-decoder model pretrained on 11 Indic languages and English,
  evaluated for potential advantages on South Asian named entities and
  place names.
\item
  \emph{mT5-Base} (\citeproc{ref-xue2021}{Xue et al. 2021}): A
  multilingual T5 variant pretrained on 101 languages at 300M
  parameters.
\item
  \emph{NT5-Small} (\citeproc{ref-zhong2023}{Zhong, Dhuliawala, and
  Stoehr 2023}): A numeracy-augmented T5 variant with a pretraining
  objective designed to improve numeric reasoning.
\item
  \emph{T5-XL-QLoRA} (\citeproc{ref-dettmers2023}{Dettmers et al.
  2023}): A 3B parameter T5 model fine-tuned using quantized low-rank
  adaptation, included as a ceiling reference.
\end{itemize}

All models were fine-tuned using the Adafactor optimizer with a learning
rate of \(3 \times 10^{-5}\), a batch size of 8, and a maximum of 10
epochs with early stopping patience of 2. Input sequences were tokenized
to a maximum of 512 tokens. Generated outputs were capped at 16 tokens,
sufficient to accommodate any plausible fatality count. The best
checkpoint was selected based on validation loss, with a fixed random
seed of 42 across all experiments.

\subsection{Decoder Models}\label{decoder-models}

I evaluate three open-source instruction-tuned decoder models plus a
proprietary ceiling reference. All models are evaluated in prompting
mode on the same held-out test set, with no parameter updates.

\begin{itemize}
\tightlist
\item
  \emph{Llama-3.1-8B-Instruct} (\citeproc{ref-dubey2024}{Dubey et al.
  2024}): An 8B parameter decoder model instruction-tuned for
  conversational and task-following use. This is the primary model in
  the LLM track.
\item
  \emph{Mistral-7B} (\citeproc{ref-jiang2023mistral}{Jiang et al. 2023})
  and \emph{Mixtral-8×7B} (\citeproc{ref-jiang2024mixtral}{Jiang et al.
  2024}): Comparator models at 7B and 56B effective parameters
  respectively.
\item
  \emph{GPT-4o-mini} (\citeproc{ref-openai2023}{OpenAI 2023}):
  Proprietary API model included as a ceiling reference.
\end{itemize}

All models receive the same baseline prompt (L0):

\begin{quote}
How many people were killed? Answer with only a number. Return JSON
exactly as: \{``fatalities'': \textless integer\textgreater\}. If no
fatalities are mentioned, use 0.
\end{quote}

Generation was capped at 48 tokens. Responses were parsed by extracting
the integer value from the JSON field; responses that could not be
parsed were mapped to 0.\footnote{Prompt non-compliance rates were low
  across all models; see the supplementary materials for the full parser
  reliability analysis.}

\subsection{Encoder Baseline}\label{encoder-baseline}

To contextualize the generative model results, I also evaluate an
encoder-based baseline combining ConfliBERT with a Poisson regression
head. ConfliBERT (\citeproc{ref-hu2022}{Hu et al. 2022}) is a BERT-base
model pretrained on a large corpus of political violence and
conflict-related text, making it the natural encoder-side reference
point for tasks in this domain. A linear regression head is appended to
the encoder's sequence-level representation and trained to predict the
log-rate of a Poisson distribution. At inference, predictions are
exponentiated and rounded to the nearest non-negative integer. Training
followed the same procedure as the seq2seq models except that the
standard AdamW optimizer was used with a learning rate of
\(2 \times 10^{-5}\). This baseline anchors all statistical significance
tests reported for both tracks.

\subsection{Evaluation Framework}\label{evaluation-framework}

Performance is evaluated using mean absolute error (MAE) as the primary
metric, supplemented by root mean squared error (RMSE), within-1
accuracy, within-2 accuracy, and nonzero MAE.\footnote{An alternative is
  token-level F1 (as used by Zhong, Dhuliawala, and Stoehr
  (\citeproc{ref-zhong2023}{2023})) which awards partial credit for
  string overlap between predicted and gold outputs. For integer count
  predictions, MAE better captures prediction quality by measuring error
  magnitude directly.} All metrics are reported both overall and
separately across five count bins (0, 1, 2, 3--5, and 6+). Bins 0 and 1
together account for the majority of test incidents, so a model that
fails on rarer bins can still appear competitive in aggregate.
Confidence intervals are obtained via paired bootstrap resampling with
\(n = 5{,}000\) replications.

Because baseline models fail systematically on rare high-fatality bins,
I evaluate two classes of targeted intervention. For the seq2seq track,
five training-side strategies are applied to Flan-T5-Large: weighted
sampling (S1), loss weighting (S2), targeted oversampling (S3),
back-translation augmentation via South Asian pivot languages (S4), and
T5 paraphrase augmentation (S5). For the prompting track, four
strategies are applied to Llama-3.1-8B: protocol clarification (L1),
bin-balanced few-shot examples (L2), hard-case few-shot examples (L3),
and a combined prompt (L4). Both classes of intervention are described
alongside their results in §6.

\section{Baseline Results and Failure
Diagnostics}\label{baseline-results-and-failure-diagnostics}

\subsection{Baseline Model Results}\label{baseline-model-results}

Tables \ref{tbl-seq2seq-baseline} and \ref{tbl-llm-baseline} report
overall performance for all seq2seq models and LLMs respectively.
ConfliBERT-Poisson serves as the baseline model for each set of model
evaluations. Values in bold are significantly better than
ConfliBERT-Poisson on mean absolute error (MAE), the primary metric,
using a paired bootstrap test with 5,000 replications and a threshold of
\(p < .05\). A dagger indicates that the model is not significantly
different from its group's ceiling reference: Flan-T5-XL-QLoRA for the
seq2seq models and GPT-4o-mini for the LLMs.

\begin{table}

\caption{\label{tbl-seq2seq-baseline}Death count extraction performance:
seq2seq models.}

\centering{

\fontsize{8.0pt}{9.0pt}\selectfont
\begin{tabular*}{\linewidth}{@{\extracolsep{\fill}}lrllrrlr}
\toprule
Metric & {\bfseries ConfliBERT} & T5-Base & T5-Large & IndicBART & mT5-Base & NT5-Small & {\bfseries T5-XL} \\ 
\midrule\addlinespace[2.5pt]
MAE & 0.37 & 0.27 & {\bfseries 0.16†} & 0.33 & 0.27 & 0.29 & {\bfseries 0.12} \\ 
RMSE & 2.21 & 3.21 & 1.18† & 1.73 & 1.61 & 3.11 & {\bfseries 0.85} \\ 
Within-1 & 94.6 & {\bfseries 97.7†} & {\bfseries 97.8†} & 94.9 & {\bfseries 96.3} & {\bfseries 97.3†} & {\bfseries 98.1} \\ 
Within-2 & 97.3 & {\bfseries 98.6†} & {\bfseries 98.7†} & 96.5 & 97.7 & {\bfseries 98.4†} & {\bfseries 98.7} \\ 
Nonzero MAE & 0.56 & 0.39 & {\bfseries 0.21†} & 0.42 & {\bfseries 0.30} & {\bfseries 0.39} & {\bfseries 0.15} \\ 
\bottomrule
\end{tabular*}
\begin{minipage}{\linewidth}
\vspace{.05em}
Bold = significantly better than ConfliBERT (paired bootstrap, n = 5000, p < .05). † = not significantly different from ceiling (p > .05). MAE and Nonzero MAE: lower is better. Within-1 and Within-2: higher is better.\\
\end{minipage}

}

\end{table}%

\begin{table}

\caption{\label{tbl-llm-baseline}Death count extraction performance:
large language models.}

\centering{

\fontsize{8.0pt}{9.0pt}\selectfont
\begin{tabular*}{\linewidth}{@{\extracolsep{\fill}}lrlllr}
\toprule
Metric & {\bfseries ConfliBERT} & Llama-3.1-8B & Mistral-7B & Mixtral-8x7B & {\bfseries GPT-4o-mini} \\ 
\midrule\addlinespace[2.5pt]
MAE & 0.37 & 0.23† & 0.30 & 0.30† & {\bfseries 0.13} \\ 
RMSE & 2.21 & 2.77† & 3.04 & 3.75† & {\bfseries 0.94} \\ 
Within-1 & 94.6 & {\bfseries 97.7†} & {\bfseries 97.2†} & {\bfseries 97.9†} & {\bfseries 97.9} \\ 
Within-2 & 97.3 & 98.4† & 97.8 & {\bfseries 98.5†} & {\bfseries 98.6} \\ 
Nonzero MAE & 0.56 & {\bfseries 0.19†} & {\bfseries 0.22†} & {\bfseries 0.16†} & {\bfseries 0.17} \\ 
\bottomrule
\end{tabular*}
\begin{minipage}{\linewidth}
\vspace{.05em}
Bold = significantly better than ConfliBERT (paired bootstrap, n = 5000, p < .05). † = not significantly different from ceiling (p > .05). MAE and Nonzero MAE: lower is better. Within-1 and Within-2: higher is better.\\
\end{minipage}

}

\end{table}%

Among the seq2seq models, Flan-T5-XL-QLoRA posts a ceiling MAE of 0.116
and Flan-T5-Large, the primary seq2seq model, achieves 0.156. Both are
significantly better than ConfliBERT-Poisson (0.370) on the primary
metric, and Flan-T5-Large is not significantly different from the
ceiling. T5-Base, IndicBART, mT5-Base, and NT5-Small fall between, with
MAEs ranging from 0.272 to 0.334, and none achieves significance over
ConfliBERT on overall MAE, though T5-Base, mT5-Base, and NT5-Small do
improve significantly on within-1 accuracy. The multilingual pretraining
of IndicBART and mT5-Base and the numeracy-augmented objective of
NT5-Small yield no consistent advantage over Flan-T5-Large, suggesting
that model scale and instruction fine-tuning are the more consequential
factors for this task.

Among the LLMs, GPT-4o-mini sets the ceiling at an MAE of 0.133 and is
significantly better than ConfliBERT-Poisson across all reported
metrics. Llama-3.1-8B, the primary LLM, achieves an MAE of 0.234, and
Mistral-7B (0.303) and Mixtral-8×7B (0.297) are comparable to each other
and broadly in the range of the weaker seq2seq models. None of the three
open-source LLMs achieves significance over ConfliBERT on overall MAE
despite substantially lower point estimates, a result attributable to
the high variance of absolute errors on rare high-count cases; however,
all three do improve significantly on within-1 accuracy and nonzero MAE.

Comparing across both groups, many models improve significantly over
ConfliBERT-Poisson on within-1 and within-2 accuracy, reflecting their
strong performance on the common low-count bins. The improvement on
nonzero MAE reflects a different advantage. Whereas the
ConfliBERT-Poisson model underpredicts counts due to the heavy presence
of zeros in the training data, the generative models perform more
consistently across the full range of nonzero values because they
extract counts directly from the text. On the more demanding test of
overall MAE, however, only Flan-T5-Large achieves significance among the
non-ceiling models in either group. Notably, Flan-T5-Large,
Llama-3.1-8B, and Mixtral-8×7B are each statistically indistinguishable
from their respective ceiling on MAE, meaning the data cannot rule out
that these three models perform as well as the best available in their
class. At the ceiling, the results for GPT-4o-mini (MAE 0.133) and
Flan-T5-XL-QLoRA (MAE 0.116) are broadly comparable, suggesting that
zero-shot prompting of a well-calibrated LLM is competitive with
fine-tuning a larger seq2seq model on this task.

\subsection{Bin-Level Performance}\label{bin-level-performance}

Figure~\ref{fig-heatmap-combined} decomposes performance by death count
bin, reporting exact match rates for all models across the five bins
defined in Section 4. Panel (a) shows the seq2seq models and panel (b)
shows the LLMs, each ordered from best to worst by overall MAE,
revealing patterns of bin-level accuracy that are harder to detect in
aggregate metrics.

\begin{figure}

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{satp-counts_files/figure-pdf/fig-heatmap-combined-1.pdf}}

}

\caption{\label{fig-heatmap-combined}Exact match (\%) by death count
bin. Seq2seq models (top) and LLMs (bottom), each ordered by overall MAE
(best at top). ConfliBERT-Poisson appears in both panels as a reference
baseline.}

\end{figure}%

Across both panels, all models achieve near-ceiling exact match rates on
bins 0, 1, and 2, which together account for roughly 87\% of test
incidents. However, model performance deteriorates sharply in the rare
bins. The ceiling models Flan-T5-XL-QLoRA and GPT-4o-mini reach 84.2\%
on bin 6+, but this still represents miscoding death counts of about one
in six events. The bin-level results of the other models invert the
impression from the overall tables, where Flan-T5-Large appeared to hold
a clear edge. Flan-T5-Large falls to 86.7\% exact match on bin 3-5 and
71.1\% on bin 6+, miscoding roughly one in three high-fatality events,
and for this bin every LLM outperforms it, with Llama-3.1-8B reaching
78.9\% and Mixtral-8×7B matching the ceiling at 84.2\%. Meanwhile,
ConfliBERT-Poisson collapses to 10.7\% on bin 3-5 and 28.9\% on bin 6+
due to its dependence on representative examples in the training
data.\footnote{Bin 6+ contains only 38 test observations, yielding
  confidence intervals of approximately ±8 percentage points for exact
  match rates. Individual model differences at the bin level are
  therefore within sampling noise. The overall MAE comparisons, which
  pool across all test observations, are therefore the more reliable
  basis for statistical inference.}

These patterns reveal how overall performance metrics paint an overly
flattering picture by averaging across a distribution heavily weighted
toward the common low-count bins. The comparatively high failure rates
on bins 3--5 and 6+ are largely invisible in the aggregate figures
because such events are less frequently seen in the data. Bin-level
decomposition is therefore essential for evaluating models that will be
used to construct conflict severity measures, given the potential for
masking analytically important counts.

\subsection{Diagnosing the Rare-Bin
Failures}\label{diagnosing-the-rare-bin-failures}

Next, we closely examine approximately 12 cases that nearly every model
has trouble with. These cases suggest how subsequent interventions might
improve model performance while revealing a practical limit for any
intervention.

In two cases, the ground-truth label is nonzero but the narrative
describes injuries or wounds rather than deaths, and every model returns
zero. These are arguably cases where the models are more accurate than
the labels (\citeproc{ref-northcutt2021}{Northcutt, Athalye, and Mueller
2021}). A further two cases involve labels that were updated from
follow-up reporting after the original summary was written, so the true
count exceeds any number present in the text. No prompt or training
intervention can produce a number that is not supported by the
narrative, and together these cases set a floor of four irreducible
errors on the test set.

However, other cases stemming from the models' tendency to discount
unconfirmed attacker deaths reflect a resolvable misalignment between
model behavior and the coding protocol. In three to four incidents,
security force deaths are confirmed and precise while Maoist casualties
are described as ``claimed,'' ``suspected,'' or ``bodies taken away by
colleagues.'' Human coders summed both sides, but the models apply an
implicit evidentiary discount. The following narrative illustrates this
pattern.

\begin{quote}
Two CRPF personnel were killed and four others injured during an
encounter with cadres of the CPI-Maoist in Giridih District. The
encounter followed an ambush by the Maoists on a Police patrol in the
Madhuban forest area and it reportedly continued for over 12 hours.
Police sources claimed that over a dozen Maoists were killed, but their
colleagues managed to take away the bodies. Maoists also triggered seven
landmine blasts during the encounter. (true = 14, all models predict 2)
\end{quote}

The phrase ``managed to take away the bodies'' marks a recurring
epistemic ambiguity in conflict reporting. The absence of bodies
forecloses independent verification of security force claims and we
cannot know whether the casualties were genuine, exaggerated or, as
documented in the Maoist context, reflective of ``fake encounters'' and
misclassified civilian deaths (\citeproc{ref-humanrightswatch2008}{Human
Rights Watch 2008}).\footnote{The total fatalities variable follows a
  maximalist coding protocol that includes all reported deaths on all
  sides, including attacker casualties claimed by security forces even
  where bodies were not independently confirmed. This is consistent with
  ACLED-style reporting-based coding but differs from the UCDP
  lower-bound approach, which discounts single-source security-force
  claims of combatant deaths. Models prompted without explicit
  clarification tend to apply an implicit evidentiary discount on
  claimed casualties, producing counts that are lower than the ground
  truth but consistent with stricter evidentiary standards.} These are
not straightforwardly model errors since a conservative UCDP-style
standard would produce these exact predictions, but they are misaligned
with the coding protocol in a way that can be addressed through further
instruction and demonstration.

A final pattern is specific to Flan-T5-Large. In three to four cases
where every open-source LLM predicts correctly, Flan-T5-Large overcounts
by one or two. All involve narratives that enumerate deaths across
multiple victim groups, and the model appears to double-count one group
or pick up an extraneous number from context. The following example
illustrates the pattern.

\begin{quote}
Four CPI-Maoist cadres, a Policeman and two villagers were killed in an
encounter between Maoists and Commandos of an anti-Naxal unit, C-60, in
a forest of Dhanora in Gadchiroli District. (true = 7, Flan-T5-Large
predicts 9)
\end{quote}

The LLMs handle these cases correctly, suggesting the failure reflects a
capacity limitation rather than a fundamental difficulty with the task.
Because the errors follow a consistent structural pattern, targeted
training examples, oversampling, and data augmentation strategies that
increase the model's exposure to multi-group enumeration cases may help
to address them.

\section{Improving Performance on Rare
Bins}\label{improving-performance-on-rare-bins}

Building on this diagnostic taxonomy, we evaluate a series of targeted
interventions designed to improve performance on the rare high-count
bins. The interventions are organized around the two model families
evaluated in the previous section. For the seq2seq models, we apply five
training-side strategies to Flan-T5-Large, ranging from reweighting and
oversampling to data augmentation through back-translation and
paraphrase generation. For the LLMs, we apply four prompt engineering
strategies to Llama-3.1-8B, progressively adding protocol clarification
and few-shot demonstrations. T5-XL-QLoRA and GPT-4o-mini serve as
ceiling references for the seq2seq and LLM results respectively. All
interventions were evaluated against the validation set before the test
set was touched, and the test set was evaluated once per finalized
strategy.

\subsection{Seq2seq Training
Interventions}\label{seq2seq-training-interventions}

The baseline Flan-T5-Large model miscodes roughly one in eight bin 3--5
events and nearly one in three bin 6+ events. We evaluate five
training-side strategies designed to improve performance on these rare
bins. Three modify how training examples are sampled or weighted during
fine-tuning to compensate for the skewed count distribution. Two augment
the rare-bin training data through paraphrase generation, increasing the
surface-form diversity of high-count narratives without requiring
additional annotation.

\subsubsection{Intervention Strategies}\label{intervention-strategies}

\textbf{Weighted sampling.} Standard fine-tuning samples training
examples in proportion to their frequency, which means the model sees
bin 3--5 and bin 6+ examples only rarely. Weighted random sampling
addresses this by assigning each training example a weight inversely
proportional to its bin frequency, so that rare-bin examples appear more
often within each epoch (\citeproc{ref-buda2018}{Buda, Maki, and
Mazurowski 2018}). We implement this using PyTorch's
\texttt{WeightedRandomSampler}.

\textbf{Loss weighting.} Rather than changing which examples are
sampled, loss weighting increases the training signal from rare-bin
examples by assigning higher weights to their contributions to the
cross-entropy loss (\citeproc{ref-he2009}{He and Garcia 2009}). Weights
are set inversely proportional to bin frequency, with conservative
capping to prevent extreme weights from destabilizing training. This
provides an alternative route to the same goal as weighted sampling
through a different mechanism.

\textbf{Targeted oversampling.} Weighted sampling and loss weighting
treat all rare-bin examples equally. Targeted oversampling instead
selects specific examples matching the failure patterns identified in
the previous section, such as narratives with multi-group enumeration
and narratives where attacker casualties are described as claimed or
unrecovered, and oversamples those at a higher rate. The rationale is
that increased exposure to the exact narrative structures driving the
errors may be more effective than upweighting rare bins.

\textbf{Back-translation augmentation.} Back-translation generates
paraphrases of existing training examples by translating them into a
pivot language and back into English, producing surface-form variation
while preserving the underlying content
(\citeproc{ref-sennrich2016}{Sennrich, Haddow, and Birch 2016};
\citeproc{ref-halterman2025}{Halterman 2025}). We apply back-translation
to all rare-bin training examples using Hindi, Urdu, and Bengali as
pivot languages, chosen because these languages preserve South Asian
place names and group acronyms that European pivot languages tend to
mangle.

\textbf{T5 paraphrase augmentation.} As an alternative to
back-translation, we use Flan-T5-Large to generate paraphrases of
rare-bin training examples directly in English
(\citeproc{ref-chung2022}{Chung et al. 2022};
\citeproc{ref-parolin2022b}{Parolin et al. 2022}). This produces more
diverse surface-form variation than back-translation but at the cost of
greater risk that the paraphrase alters numerically critical content.
The same rare-bin examples targeted by back-translation are augmented
here, allowing a direct comparison of the two approaches.

\subsubsection{Results}\label{results}

\begin{table}

\caption{\label{tbl-rarebin-seq2seq}Seq2seq rare-bin intervention
results (Flan-T5-Large base).}

\centering{

\fontsize{8.0pt}{9.0pt}\selectfont
\begin{tabular*}{\linewidth}{@{\extracolsep{\fill}}lllllllr}
\toprule
Metric & Baseline & Weighted & Loss Wt. & Targeted & Back-transl. & Paraphrase & {\bfseries T5-XL} \\ 
\midrule\addlinespace[2.5pt]
MAE & 0.16† & 0.26 & 0.22† & 0.24† & 0.27 & 0.27 & 0.12 \\ 
Nonzero MAE & 0.21† & 0.36 & 0.35 & 0.35 & 0.37 & 0.38 & 0.15 \\ 
Bin 3-5 MAE & 0.24† & 0.27 & 0.24 & 0.24 & 0.21† & 0.23† & 0.19 \\ 
Bin 3-5 Exact (\%) & 86.7† & 85.3 & 86.7† & 85.3 & 88.0† & 86.7† & 90.7 \\ 
Bin 6+ MAE & 1.97† & 4.08 & 3.95 & 4.05 & 4.18 & 4.34 & 1.05 \\ 
Bin 6+ Exact (\%) & 71.1† & 73.7† & 68.4 & 68.4 & 71.1 & 71.1 & 84.2 \\ 
\bottomrule
\end{tabular*}
\begin{minipage}{\linewidth}
\vspace{.05em}
Bold = significantly better than baseline model (paired bootstrap, n = 5000, p < .05). † = not significantly different from ceiling (p > .05). MAE rows: lower is better. Exact (\%) rows: higher is better.\\
\end{minipage}

}

\end{table}%

Table~\ref{tbl-rarebin-seq2seq} reports the results. The three
reweighting strategies (weighted sampling, loss weighting, and targeted
oversampling) all increase overall MAE relative to the baseline and none
improves bin 3--5 or bin 6+ exact match. All three push the model toward
higher count predictions on ambiguous narratives, increasing errors on
the common low-count cases that dominate the test set without producing
compensating gains in the rare bins. Back-translation improves on the
baseline, raising bin 3--5 exact match from 86.7\% to 88.0\% while
holding bin 6+ exact match at the baseline level, but the difference is
not statistically significant. T5 paraphrase augmentation is
directionally similar but weaker, returning bin 3--5 exact match to the
baseline level. No strategy improves bin 6+ MAE, which remains near 4.0
for all interventions against a baseline of 1.97.

These results suggest that the bin 6+ gap between Flan-T5-Large (71.1\%
exact match) and T5-XL-QLoRA (84.2\%) reflects a model capacity
constraint rather than a data imbalance problem. The failure patterns
identified in the previous section (multi-group enumeration, implicit
totals, claimed casualties) require the model to aggregate counts across
clauses and reason about what to include. These are mainly arithmetic
reasoning tasks that scale with model capacity rather than training data
volume. The T5-XL-QLoRA result, achieved without any rare-bin
intervention, suggests the gap is closeable with a larger model, and
that reweighting and augmentation cannot substitute for the capacity of
a much larger model.

\subsection{LLM Prompt Engineering
Interventions}\label{llm-prompt-engineering-interventions}

The baseline Llama-3.1-8B model miscodes roughly one in ten bin 3--5
events and roughly one in five bin 6+ events. We evaluate four prompt
engineering strategies designed to improve performance on these rare
bins. One adds a protocol clarification to the system prompt,
instructing the model to count claimed attacker casualties even when
bodies were not recovered. Three vary the content and composition of
few-shot demonstrations, progressively targeting the narrative
structures most associated with high-count miscoding. GPT-4o-mini serves
as the ceiling reference for the LLM track. The full text of the prompts
is available in Appendix B.

\subsubsection{Intervention Strategies}\label{intervention-strategies-1}

\textbf{Protocol clarification.} The baseline prompt does not specify
how to handle attacker casualties that are described as claimed or
unrecovered. This strategy adds a single instruction to the system
prompt directing the model to count all reported deaths on all sides,
including claimed attacker casualties even when bodies were not
recovered. This directly encodes the maximalist counting protocol
established in the data collection design.

\textbf{Bin-balanced few-shot.} This strategy replaces the zero-shot
baseline with five demonstrations sampled to cover the full range of
death counts, including at least one example from each bin. The goal is
to make the count range salient to the model before it reads the target
narrative, without specifically targeting the failure patterns
identified earlier.

\textbf{Hard-case few-shot.} Rather than sampling for bin coverage, this
strategy selects four demonstrations that exemplify the specific
narrative structures driving miscoding in the baseline, including events
where attacker casualties are described as claimed or inferred and
events where deaths must be summed across multiple armed groups. The
examples are drawn from the validation set and excluded from evaluation.

\textbf{Combined few-shot.} This strategy combines the bin-balanced and
hard-case example sets (nine demonstrations total) with the protocol
clarification instruction. The bin-balanced examples provide count-range
calibration, the hard-case examples anchor the difficult narrative
structures concretely, and the protocol instruction aligns the model on
what to count.

\subsubsection{Results}\label{results-1}

\begin{table}

\caption{\label{tbl-rarebin-llms}LLM prompt engineering results
(Llama-3.1-8B base).}

\centering{

\fontsize{8.0pt}{9.0pt}\selectfont
\begin{tabular*}{\linewidth}{@{\extracolsep{\fill}}llllllr}
\toprule
Metric & Baseline & Protocol & Bin-shot & Hard-shot & Combined & {\bfseries GPT-4o-mini} \\ 
\midrule\addlinespace[2.5pt]
MAE & 0.23† & 0.32 & {\bfseries 0.20†} & {\bfseries 0.11†} & {\bfseries 0.11†} & 0.13 \\ 
Nonzero MAE & 0.19† & 0.20† & 0.15† & 0.14† & 0.13† & 0.17 \\ 
Bin 3-5 MAE & 0.20† & 0.23† & 0.28 & 0.20† & 0.28 & 0.16 \\ 
Bin 3-5 Exact (\%) & 90.7† & 88.0† & 88.0 & 90.7† & 88.0 & 93.3 \\ 
Bin 6+ MAE & 1.53† & 0.95† & 0.97† & 0.84† & {\bfseries 0.63†} & 1.24 \\ 
Bin 6+ Exact (\%) & 78.9† & 76.3† & 78.9† & 81.6† & {\bfseries 89.5†} & 84.2 \\ 
\bottomrule
\end{tabular*}
\begin{minipage}{\linewidth}
\vspace{.05em}
Bold = significantly better than baseline model (paired bootstrap, n = 5000, p < .05). † = not significantly different from ceiling (p > .05). MAE rows: lower is better. Exact (\%) rows: higher is better.\\
\end{minipage}

}

\end{table}%

Table~\ref{tbl-rarebin-llms} reports the results. The protocol
clarification strategy is counterproductive. Overall MAE rises from
0.235 to 0.318 and bin 6+ exact match falls from 78.9\% to 76.3\%.
However, the few-shot strategies improve performance at every step.
Bin-balanced demonstrations reduce overall MAE to 0.199 while holding
bin 6+ exact match at the baseline level. Hard-case demonstrations
reduce overall MAE further to 0.113 and raise bin 6+ exact match to
81.6\%, the strongest rare-bin result among all Llama strategies. The
combined strategy improves on all three metrics, with overall MAE
falling to 0.107, bin 6+ exact match rising to 89.5\%, and bin 3--5
exact match holding at 88.0\%. All three figures nominally exceed
GPT-4o-mini, though none of the differences are statistically
significant.

These results suggest that demonstrations rather than instructions are
the active ingredient in few-shot prompting for this task. The protocol
clarification instruction specifies what to count but provides no
examples of how to handle the ambiguous cases that drive miscoding in
the baseline, including claimed casualties, implied totals, and
multi-group enumeration. Without anchoring examples, the model applies
the instruction too broadly, increasing predicted counts on cases where
deaths are genuinely uncertain. The hard-case demonstrations address
uncertainty by showing the model how to handle each failure type, while
the protocol instruction adds value within the combined prompt because
the examples first establish when claimed casualties should be counted
and when they should not.

\section{Discussion}\label{discussion}

The results of this study suggest a favorable picture of automated death
count extraction. Generative models substantially outperform the encoder
baseline across both tracks, and on the common low-count events that
make up the large majority of the test set, most approaches achieve
near-ceiling performance. However, the bin-level decomposition
complicates this picture. Aggregate MAE on a heavily skewed distribution
is dominated by the low-count bins where all models perform well, and a
model that fails consistently on high-fatality events can appear
competitive in aggregate. The bin-level results make this failure
visible. Models that look broadly comparable on overall MAE differ
substantially on exact match rates for the rarer, higher-count bins.
Consequently, our first important finding is that automated event coding
papers reporting count fields should decompose performance across the
count distribution rather than relying on aggregate error alone.

\subsubsection{Addressing Rare Bin
Errors}\label{addressing-rare-bin-errors}

With respect to addressing rare-bin errors, LLMs are more responsive to
interventions than seq2seq models, and the nature of effective
interventions differs between the two families. A protocol clarification
instruction in isolation is counterproductive for LLMs, pushing the
model to overcount on ambiguous cases without anchoring it to the
specific narrative structures that drive miscoding. More targeted
prompting strategies that feature demonstrations of hard cases prove
considerably more effective. For seq2seq models, reweighting and
oversampling strategies are similarly counterproductive, raising overall
MAE without improving rare-bin performance. Back-translation
augmentation produces directional improvement on bin 3--5 and is the
only training-side strategy worth applying. The bin 6+ gap between
Flan-T5-Large and the ceiling model reflects a capacity constraint that
training-side interventions cannot close.

Not all rare-bin errors are resolvable through model adjustment,
however. An analysis of the rare-bin errors revealed that a small number
of cases have correct counts that are either absent from the text or
inconsistent with the ground-truth label, and no prompt or training
intervention can address them. Setting those cases aside, the best
models approach near-perfect performance on bin 6+. Because rare events
are few by definition, targeted manual review of high-count predictions
is feasible in a way that bulk review is not. A reasonable workflow is
to run the model across all events and reserve manual inspection for
predictions above a certain count threshold, where the number of cases
is small enough to examine and the cost of error is largest.

\subsubsection{Model Behavior and Practical
Implications}\label{model-behavior-and-practical-implications}

A consistent pattern in the study's results is that models apply an
implicit evidentiary standard closer to UCDP-style conservative coding
than to the ACLED-style maximalist protocol used in this dataset. When
attacker casualties are described as claimed or unrecovered, models tend
to discount them, producing predictions that align with a lower-bound
evidentiary threshold rather than the reporting-based coding that the
ground-truth labels reflect. This default would not surface without
case-level diagnostic analysis and is invisible in aggregate metrics. A
protocol clarification instruction alone does not override it. The
results for the protocol clarification strategy show that explicitly
instructing the model to count claimed casualties worsens overall
performance, suggesting the default is more deeply internalized than a
simple instruction can address. Researchers should decide which
evidentiary standard their system is meant to apply and use
demonstrations from the target corpus to teach the model how to
implement it. Without this step, automated systems will default toward a
conservative lower-bound standard regardless of the researcher's
intentions.

Our findings also suggest practical considerations regarding model
choice that researchers should weigh alongside performance. Scaling
seq2seq models to close the bin 6+ gap requires QLoRA fine-tuning, which
demands substantial GPU resources and non-trivial configuration.
GPT-4o-mini is the simplest deployment path, but it is a proprietary
paid service and incident data must be transmitted to an external
provider. Llama-3.1-8B with combined few-shot prompting achieves the
strongest rare-bin performance without any fine-tuning, runs on modest
local hardware, keeps data within the researcher's environment, and is
free to use. The learning curve is steeper than a simple API call, but
for researchers handling sensitive data or working without a cloud
budget, the open-source route is both capable and practical.

\subsubsection{Limitations and Future
Work}\label{limitations-and-future-work}

Several limitations bear on the interpretation of our results. All
experiments use incidents from the Indian Maoist conflict as reported by
SATP, and generalizability to other conflicts and reporting conventions
requires validation on additional corpora. The focused single-conflict
corpus enables the diagnostic precision that motivates the experimental
design, but it limits the scope of what can be claimed about automated
count extraction in other settings. Results for the API-based models are
tied to specific model versions that may change without notice, and
replication packages should pin model versions accordingly. The
component columns recording deaths by actor group were used to verify
the coding protocol but were not analyzed as separate extraction
targets, which would allow direct testing of the evidentiary asymmetry
hypothesis and enable comparison with UCDP-AEC's per-field schema. The
bin-level exact match figures should be interpreted alongside the
aggregate MAE results, which pool across all test observations and
provide the primary basis for statistical inference. The small number of
bin 6+ observations means that bin-level comparisons carry wider margins
of uncertainty than the overall metrics.

The most natural extension of this work is per-side decomposition,
treating security force, Maoist, and civilian death counts as separate
extraction targets rather than summing to a total. This would allow
direct testing of the evidentiary asymmetry hypothesis and enable
comparison with UCDP-AEC's per-field schema. The same bin-level
evaluation framework applies to other count fields in the SATP corpus,
including injuries, arrests, and surrenders, where the distributional
challenge is identical. On the modeling side, full fine-tuning of larger
seq2seq models would test whether the bin 6+ capacity gap closes with
scale, and chain-of-thought prompting may address the multi-group
enumeration cases that currently drive miscoding in both model families.

\section{Conclusion}\label{conclusion}

This paper has argued that automated death count extraction deserves to
be treated as a primary research problem in conflict event coding rather
than as a secondary question bundled into broader information extraction
systems. Fatality counts are central to how conflict severity,
escalation, and human costs are measured. The data are readily
available, yet highly skewed. Most incident reports describe zero or one
death, while the rarer high-fatality events carry disproportionate
analytical weight. Under these conditions, an automated system can
appear strong in aggregate while still failing on the very cases that
matter most for substantive inference.

To address this gap, I evaluated death count extraction on a corpus of
roughly 10,000 SATP incident summaries using two model families:
fine-tuned seq2seq models and prompted instruction-tuned LLMs. Both
tracks were compared to a ConfliBERT-Poisson baseline and evaluated on
the same held-out test set. The central methodological contribution of
the paper is the use of bin-level evaluation alongside aggregate
metrics. By decomposing performance across the count distribution into
bins of 0, 1, 2, 3--5, and 6+, the analysis reveals that strong
performance on common low-count events does not imply reliable
performance on rare, high-fatality incidents.

The baseline experiments show that generative approaches are clearly
more effective than the encoder baseline for this task. Flan-T5-Large
and GPT-4o-mini perform strongly overall, and most generative models
achieve near-ceiling results on the low-count bins that dominate the
test set. But the bin-level analysis complicates this favorable picture.
Performance deteriorates sharply in bins 3--5 and especially 6+, and
models that look broadly competitive in aggregate differ much more
substantially once attention shifts to rare high-fatality cases.
Case-level diagnostics further show that these failures are not all of
the same kind. Some reflect irreducible limits in the source text or
ground-truth labels, while others arise from recurring and potentially
addressable problems, including ambiguity around claimed attacker deaths
and errors in aggregating counts across multiple victim groups.

The intervention experiments clarify which of these rare-bin failures
can be reduced and by what means. On the seq2seq side, reweighting and
oversampling strategies do not improve high-count performance and often
worsen overall MAE by pushing the model toward overprediction on
ambiguous cases. Back-translation provides modest directional
improvement on bin 3--5, but no training-side intervention closes the
remaining gap on bin 6+. The results therefore suggest that the hardest
seq2seq failures are primarily constrained by model capacity rather than
by class imbalance alone. On the LLM side, the pattern is different. A
protocol clarification instruction by itself is counterproductive, but
few-shot prompting with targeted hard-case examples substantially
improves performance. The combined prompt produces the strongest results
for Llama-3.1-8B, bringing its rare-bin performance to a level
comparable to GPT-4o-mini and, on point estimates, slightly above it.

Taken together, these findings have both methodological and practical
implications for conflict research. Methodologically, work on automated
extraction of count fields should not rely on aggregate error analysis
alone but instead must reflect the shape of the underlying distribution
and the substantive importance of rare events. Practically, the results
suggest that automated death count extraction is already usable,
especially when paired with generative models, but it should be deployed
with attention to the special difficulty of high-fatality cases. A
realistic workflow is therefore not fully automated replacement of human
coding, but model-assisted extraction combined with targeted review of
the relatively small number of high-count predictions where error is
most consequential. More broadly, the paper shows that progress on
conflict event count extraction depends not only on stronger models, but
also on evaluation frameworks and intervention strategies that are
explicitly designed for rare but analytically decisive events.

\newpage

\section{Appendix}\label{appendix}

This appendix provides supplementary material for the main text.
Appendix A presents representative hard cases that motivated the error
taxonomy used in Sections 5 and 7. Appendix B documents the full
prompting strategies used in the LLM intervention study. Appendix C
summarizes parser reliability and format compliance. Appendix D presents
supplementary bootstrap figures that support the main comparisons.

\subsection{Appendix A. Hard Cases Discussed in the Main
Analysis}\label{appendix-a.-hard-cases-discussed-in-the-main-analysis}

The 12 cases below map directly onto the diagnostic discussion in
Section 5, grouped by error type. Model abbreviations: GPT =
GPT-4o-mini, Llama = Llama-3.1-8B, Mixtral = Mixtral-8×7B, T5-XL =
Flan-T5-XL-QLoRA, T5-L = Flan-T5-Large.

\medskip\noindent \textbf{Probable labeling errors (2 cases).} In both
incidents the narrative describes wounds or injuries rather than deaths,
and every model correctly returns zero.

\smallskip\noindent \emph{301140802} --- gold = 5; all models predict 0.

\begin{quote}
Five CRPF personnel were wounded in an ambush by armed Maoists in a
forest in the Narayanpur District of Chhattisgarh. About 150 Maoists
attacked a joint Police party of the CRPF and District forces when the
security force personnel were on a de-mining and area dominance
operation in the Jharghati jungle, about 350 kilometers from State
capital Raipur, the District Superintendent of Police Ajay Yadav said.
\end{quote}

\noindent \emph{308241302} --- gold = 3; all models predict 0.

\begin{quote}
Three District Police personnel, including a Head Constable, were
injured in an encounter with CPI-Maoist cadres in Kondagaon District. SP
D Shravan said a joint team of District Police and Chhattisgarh Armed
Forces had left Bayanar Police Station for a search operation in nearby
areas but the Maoists hiding near Mungawal Kotapara village started
firing on the Police personnel as soon as the Police team reached near
the village.
\end{quote}

\medskip\noindent \textbf{Revised counts from follow-up reporting (2 cases).}
The gold label was updated after a follow-up report, so the true count
exceeds any number stated in the original narrative.

\smallskip\noindent \emph{304061001} --- gold = 84; GPT 76, Llama 76,
Mixtral 76, T5-XL 76, T5-L 79. The narrative supports 76 (75 CRPF + 1
SP); the label was updated to 84 from a follow-up source recording 8
additional deaths.

\begin{quote}
75 CRPF personnel and a State Policeman were killed in an attack by
about 1000 CPI-Maoist cadres in Dantewada District.
\end{quote}

\noindent \emph{807021301} --- gold = 6; all models predict 5. The
narrative supports 5 (SP + 4 constables); the sixth death was likely
recorded in a follow-up report.

\begin{quote}
Pakur District SP Amarjit Balihar (45) and four other Policemen were
killed in an ambush by CPI-Maoist cadres in Kathikund forest area of
Dumka District of Jharkhand. Balihar was returning from a meeting with
DIG Priya Dubey in Dumka when his vehicle was attacked by Maoists
between 2.30 and 3pm.
\end{quote}

\medskip\noindent \textbf{Unconfirmed attacker deaths (4 cases).} Models
count confirmed security force deaths but discount claimed Maoist
casualties, particularly when bodies were not recovered.

\smallskip\noindent \emph{802080801} --- gold = 14; all models predict
2. Models count 2 confirmed CRPF deaths and exclude the 12+ Maoist
deaths described as claimed with bodies taken away.

\begin{quote}
Two CRPF personnel were killed and four others injured during an
encounter with cadres of the CPI-Maoist in Giridih District. The
encounter followed an ambush by the Maoists on a Police patrol in the
Madhuban forest area and it reportedly continued for over 12 hours.
Police sources claimed that over a dozen Maoists were killed, but their
colleagues managed to take away the bodies. Maoists also triggered seven
landmine blasts during the encounter.
\end{quote}

\noindent \emph{1210080901} --- gold = 33; GPT 18, Llama 18, Mixtral 18,
T5-XL 21, T5-L 19. Models count 18 confirmed police deaths and exclude
15 Maoist deaths described as ``Police sources said\ldots also killed.''

\begin{quote}
Cadres of the CPI-Maoist killed at least 18 Policemen, including
Sub-Inspector C. S. Deshmukh, in an ambush in the dense forests near
Laheri Police Station in Gadchiroli District. The incident occurred when
a 40 member Police party came under heavy fire from 150 to 200 Maoists
at about 1pm (IST) when it was returning after undertaking search
operations following intelligence inputs that Maoists had assembled in
the area. District Collector Atul Patne told, ``As many as two platoons
of BSF (50 personnel) and additional Police force was rushed to the spot
and they could manage to save the rest of the Policemen caught in the
heavy fire.'' Police sources said that about 15 Maoists were also killed
in the gun battle.
\end{quote}

\noindent \emph{1402150801} --- gold = 18; GPT 15, Llama 15, Mixtral 15,
T5-XL 15, T5-L 15. Models count 15 police and civilian deaths but
exclude 3 Maoist deaths described as claimed with bodies not recovered.

\begin{quote}
14 Police personnel and a civilian were killed and four Policemen were
wounded when around 500 heavily armed cadres of the CPI-Maoist attacked
a Police Training School (PTS), the District armoury and District Police
station in co-ordinated attacks near Daspalla in the Nayagarh District
at around 10.45pm (IST). They also took away a cache of arms and
ammunition in a bus they had hijacked in the District, about 100-km from
State capital Bhubaneswar. Police sources claimed that three Maoists
were also killed in the incident. However, their bodies have not been
recovered and it is suspected that the Maoists before fleeing took away
the bodies of their slain comrades. Before launching the attack, the
Maoists, speaking in Hindi and Telugu, and suspected to be from
neighbouring Chhattisgarh and Andhra Pradesh, announced that they would
not harm the public as their target was the Police. The Police suspect
it to be the handy work of Sabyasachi Panda, the CPI-Maoist
Andhra-Orissa `secretary'. Meanwhile, a red alert has been sounded in
the State and the Police have started combing operations in the
neighbouring Districts of Phulbani, Gajapati, Rayagada and Malkangiri in
Orissa. The attack was the first of its kind in coastal Orissa. The
District armoury and PTS were virtually emptied by the Maoists, the
Police said.
\end{quote}

\noindent \emph{1405191101} --- gold = 24; GPT 16, Llama 16, Mixtral 16,
T5-XL 24, T5-L 4. Models undercount ``over 20 Maoists killed'' across
two encounters; T5-XL-QLoRA is the only model to extract the correct
total.

\begin{quote}
Four Police personnel, including two SPOs and over 20 CPI-Maoist cadres
were killed in two different encounters in Gadchiroli District. ``At
around 7.30 a.m. in Nalgonda forest, four C60 commando search parties
were ambushed by Naxalites. The ambush and exchange of fire went on for
more than 1 hour and 15 minutes. One Police constable, Chinna Gilla
Venta (30), was killed and two were injured,'' Rahul Sheth, Gadchiroli
ASP Operations said. Sheth said 12-14 Naxals were killed. ``When our
Police parties chased the Naxals, they ran away and left behind two
bodies. An AK-47 magazine was found on one of the bodies, indicating
that the deceased was a senior commander.''
\end{quote}

\medskip\noindent \textbf{T5-Large overcount: multi-group arithmetic (4 cases).}
All LLMs return the correct total; Flan-T5-Large overcounts by one or
two, apparently double-counting one group when deaths are enumerated
across multiple actor categories.

\smallskip\noindent \emph{1204121301} --- gold = 7; GPT 7, Llama 7,
Mixtral 7, T5-XL 7, T5-L 9.

\begin{quote}
Four CPI-Maoist cadres, a Policeman and two villagers were killed in an
encounter between Maoists and Commandos of an anti-Naxal unit, C-60, in
a forest of Dhanora in Gadchiroli District.
\end{quote}

\noindent \emph{1205300501} --- gold = 8; GPT 8, Llama 8, Mixtral 8,
T5-XL 8, T5-L 9.

\begin{quote}
Seven Police personnel and a civilian are killed in a landmine blast
triggered by the CPI-Maoist on Deori-Chichgad road in the Gondia
District.
\end{quote}

\noindent \emph{306010501} --- gold = 6; GPT 6, Llama 6, Mixtral 6,
T5-XL 6, T5-L 7.

\begin{quote}
Assistant Commander of the CRPF, R K Mishra, and five other CRPF
personnel are killed when the Maoists ambushed a CRPF combing party near
Injaram in Dantewada District.
\end{quote}

\noindent \emph{305171501} --- gold = 5; GPT 5, Llama 5, Mixtral 5,
T5-XL 5, T5-L 6. The overcount here is triggered by a ``succumbed to
injuries'' clause rather than multi-group enumeration, but the pattern
is the same: T5-Large picks up an extraneous count that other models
correctly ignore.

\begin{quote}
Three Policemen and two CPI-Maoist cadres were killed in an encounter in
Bijapur District. The encounter took place early in the morning near
Ponjed at Mirjur in Gangaloor Police Station area where a team of STF
and District Police Force was conducting an anti-Maoist operation. STF
Constable Sitaram Kunjam and Assistant Constable of the District Force
Moti Ram were killed on the spot. Another Constable Payku Ram Poyam
succumbed to his injuries while he was being taken to Jagdalpur. Among
the Maoist killed was a senior guerilla fighter Hemla Masa alias Vijay,
`commander of Company 2' of West Bastar Division of CPI-Maoist. ADG
(Naxal Operations), R K Vij, said: ``Fifteen rounds of AK-47, nine
shells of Under Barrel Grenade Launcher, a 12 bore rifle and a wireless
set were recovered from him.'' Speaking on rebel presence in the area,
Vij said the area was ``highly-affected''. ``Our team had gone for an
operation when the Maoists opened fire at them. Our jawans retaliated.
We have recovered bodies of two uniformed Maoists,'' he added.
\end{quote}

\subsection{Appendix B. Full Prompting
Strategy}\label{appendix-b.-full-prompting-strategy}

This appendix records the exact prompt variants used in the LLM
intervention study reported in Section 6. GPT-4o-mini used the same
\texttt{L1} instruction text when that ceiling-reference variant was
evaluated; there was no separate GPT-specific wording.

\subsubsection{B.1 L0 Baseline Prompt}\label{b.1-l0-baseline-prompt}

The baseline prompt is a zero-shot extraction instruction with a strict
JSON output schema.

\begin{quote}
How many people were killed? Answer with only a number. Return JSON
exactly as: \{``fatalities'': \textless integer\textgreater\}. If no
fatalities are mentioned, use 0.

Text: \{incident\_summary\}

Answer:
\end{quote}

\subsubsection{B.2 L1 Protocol Clarification
Prompt}\label{b.2-l1-protocol-clarification-prompt}

This variant adds a single sentence aligning the model with the
maximalist coding protocol used in the dataset by instructing it to
include claimed attacker deaths.

\begin{quote}
How many people were killed? Answer with only a number. Return JSON
exactly as: \{``fatalities'': \textless integer\textgreater\}. If no
fatalities are mentioned, use 0. Count all reported deaths on all sides,
including claimed attacker casualties even if bodies were not recovered.

Text: \{incident\_summary\}

Answer:
\end{quote}

\subsubsection{B.3 L2 Bin-Balanced Few-Shot
Prompt}\label{b.3-l2-bin-balanced-few-shot-prompt}

This variant prepends one clear example from each count bin (\texttt{0},
\texttt{1}, \texttt{2}, \texttt{3-5}, and \texttt{6+}) to make the count
range salient before the target narrative is processed.

\begin{quote}
How many people were killed? Answer with only a number. Return JSON
exactly as: \{``fatalities'': \textless integer\textgreater\}. If no
fatalities are mentioned, use 0. Count all reported deaths on all sides,
including claimed attacker casualties even if bodies were not recovered.

Text: Seven CRPF personnel were injured in a landmine blast in the
Bijapur District. Answer: \{``fatalities'': 0\}

Text: CPI-Maoists killed one villager in Garwah district. Answer:
\{``fatalities'': 1\}

Text: CPI-Maoist cadres kill two farmers in the Rohtas District. Answer:
\{``fatalities'': 2\}

Text: Three persons were killed and five others injured by the
CPI-Maoist at Khaira village in Lakhisarai District. Answer:
\{``fatalities'': 3\}

Text: Seven CPI-Maoist cadres were killed in a gun battle with SFs in
Latehar District. Answer: \{``fatalities'': 7\}

Text: \{incident\_summary\}

Answer:
\end{quote}

\subsubsection{B.4 L3 Hard-Case Few-Shot
Prompt}\label{b.4-l3-hard-case-few-shot-prompt}

This variant uses four examples chosen to match the recurrent failure
modes identified in the baseline diagnostics: multi-group arithmetic,
claimed attacker deaths, and delayed deaths from injuries.

\begin{quote}
How many people were killed? Answer with only a number. Return JSON
exactly as: \{``fatalities'': \textless integer\textgreater\}. If no
fatalities are mentioned, use 0. Count all reported deaths on all sides,
including claimed attacker casualties even if bodies were not recovered.

Text: Three Maoists and a civilian were killed during an encounter at
Bhejji locality in the Dantewada District. Answer: \{``fatalities'': 4\}

Text: Police claimed to have killed six cadres of the CPI-Maoist in an
encounter at Bangudwa Naktaia hills in the Gaya District. The Deputy
Superintendent of Police said that dead bodies of the slain Maoists
could not be recovered from the encounter site as these were taken away
by their colleagues. Answer: \{``fatalities'': 6\}

Text: Three troopers of CoBRA were killed and at least 15 others were
injured in an encounter with CPI-Maoist cadres in Sukma District.
Officials said while two Commandos had succumbed to bullet injuries on
March 3, their colleague died on March 4. At least 15 others were
injured. Answer: \{``fatalities'': 3\}

Text: Five security personnel, including two STF troopers, were injured
when CPI-Maoist cadres ambushed a team of SFs in Sukma District. Police
also claimed to have gunned down at least 15 Maoists in the encounter
although no bodies were recovered from the spot. Answer:
\{``fatalities'': 15\}

Text: \{incident\_summary\}

Answer:
\end{quote}

\subsubsection{B.5 L4 Combined Few-Shot
Prompt}\label{b.5-l4-combined-few-shot-prompt}

The combined prompt merges the five bin-balanced examples from L2 with
the four hard-case examples from L3, for a total of nine demonstrations.

\begin{quote}
How many people were killed? Answer with only a number. Return JSON
exactly as: \{``fatalities'': \textless integer\textgreater\}. If no
fatalities are mentioned, use 0. Count all reported deaths on all sides,
including claimed attacker casualties even if bodies were not recovered.

Text: Seven CRPF personnel were injured in a landmine blast in the
Bijapur District. Answer: \{``fatalities'': 0\}

Text: CPI-Maoists killed one villager in Garwah district. Answer:
\{``fatalities'': 1\}

Text: CPI-Maoist cadres kill two farmers in the Rohtas District. Answer:
\{``fatalities'': 2\}

Text: Three persons were killed and five others injured by the
CPI-Maoist at Khaira village in Lakhisarai District. Answer:
\{``fatalities'': 3\}

Text: Seven CPI-Maoist cadres were killed in a gun battle with SFs in
Latehar District. Answer: \{``fatalities'': 7\}

Text: Three Maoists and a civilian were killed during an encounter at
Bhejji locality in the Dantewada District. Answer: \{``fatalities'': 4\}

Text: Police claimed to have killed six cadres of the CPI-Maoist in an
encounter at Bangudwa Naktaia hills in the Gaya District. The Deputy
Superintendent of Police said that dead bodies of the slain Maoists
could not be recovered from the encounter site as these were taken away
by their colleagues. Answer: \{``fatalities'': 6\}

Text: Three troopers of CoBRA were killed and at least 15 others were
injured in an encounter with CPI-Maoist cadres in Sukma District.
Officials said while two Commandos had succumbed to bullet injuries on
March 3, their colleague died on March 4. At least 15 others were
injured. Answer: \{``fatalities'': 3\}

Text: Five security personnel, including two STF troopers, were injured
when CPI-Maoist cadres ambushed a team of SFs in Sukma District. Police
also claimed to have gunned down at least 15 Maoists in the encounter
although no bodies were recovered from the spot. Answer:
\{``fatalities'': 15\}

Text: \{incident\_summary\}

Answer:
\end{quote}

The logic of the prompt sequence is cumulative. L1 attempts protocol
alignment by instruction alone. L2 adds count-range calibration. L3 adds
demonstrations of the hardest narrative structures. L4 combines both
forms of guidance and was the strongest open-source prompt variant in
the final evaluation.

\subsection{Appendix C. Parser Reliability
Analysis}\label{appendix-c.-parser-reliability-analysis}

The paper's main results depend on extraction quality rather than format
artifacts only if parser failures are rare and separable from genuine
model error. That condition is satisfied here. The count-extraction
workflow uses different parsers for the two model families because the
expected output formats differ. The LLM pipeline asks for JSON and first
searches for a \texttt{"fatalities"} key, while the seq2seq pipeline
expects plain numeric output and uses a simpler integer-oriented parser.

\subsubsection{C.1 Format Compliance}\label{c.1-format-compliance}

Observed format compliance was near-perfect for all models, with one
notable behavioral difference: Llama-3.1-8B almost always emitted valid
JSON followed by extra commentary rather than returning the requested
JSON string alone. Because the JSON object appeared first, the parser
recovered the intended value without difficulty.

\paragraph{Table C1. LLM output
compliance}\label{table-c1.-llm-output-compliance}

\begin{longtable}[]{@{}lrrr@{}}
\toprule\noalign{}
Model & Strict JSON & JSON + trailing text & No JSON \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
GPT-4o-mini & 100.0\% & 0.0\% & 0.0\% \\
Mistral-7B & 99.8\% & 0.1\% & 0.1\% \\
Mixtral-8x7B & 99.9\% & 0.0\% & 0.1\% \\
Llama-3.1-8B & 0.0\% & 100.0\% & 0.0\% \\
\end{longtable}

\paragraph{Table C2. Seq2seq output
compliance}\label{table-c2.-seq2seq-output-compliance}

\begin{longtable}[]{@{}lrrr@{}}
\toprule\noalign{}
Model family & Number only & Number + extra text & No number \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Flan-T5 base/large/XL-QLoRA & 100.0\% & 0.0\% & 0.0\% \\
mT5-base, NT5-small & 100.0\% & 0.0\% & 0.0\% \\
IndicBART & 0.0\% & 99.9\% & 0.1\% \\
\end{longtable}

IndicBART's noncompliance is due to tokenizer artifacts around the
predicted numeral rather than genuine uncertainty about the task. The
digit extraction fallback recovers the correct count in all but one edge
case.

\subsubsection{C.2 Parse Failures}\label{c.2-parse-failures}

Actual parse failures were extremely rare.

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\linewidth - 8\tabcolsep) * \real{0.1667}}
  >{\raggedleft\arraybackslash}p{(\linewidth - 8\tabcolsep) * \real{0.2222}}
  >{\raggedleft\arraybackslash}p{(\linewidth - 8\tabcolsep) * \real{0.2222}}
  >{\raggedleft\arraybackslash}p{(\linewidth - 8\tabcolsep) * \real{0.2222}}
  >{\raggedright\arraybackslash}p{(\linewidth - 8\tabcolsep) * \real{0.1667}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Pipeline
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Outputs evaluated
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Parse failures
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Failure rate
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Notes
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
LLM & 3,436 & 2 & 0.06\% & Both failures were echoed-text outputs from
Mistral-7B and Mixtral-8x7B on the same incident. \\
Seq2seq & evaluated seq2seq prediction outputs & 0 & 0.00\% & No true
parse failures observed. \\
\end{longtable}

The main limitation of the original LLM parser was not unreliability but
silence: when extraction failed, the parser returned \texttt{0} without
recording that the zero came from a parse failure rather than from a
model prediction. This has now been addressed in the code by allowing
the parser to return metadata, including \texttt{parse\_success},
\texttt{parse\_method}, and
\texttt{defaulted\_to\_zero\_due\_to\_parse\_failure}. The substantive
results in the paper are unaffected because the failures are too rare to
move any reported metric.

\subsubsection{C.3 Implication for the Main
Results}\label{c.3-implication-for-the-main-results}

The parser analysis supports two conclusions. First, the model
comparisons in the paper are not driven by formatting artifacts. Second,
prompt improvements in Section 6 should be interpreted as changes in
extraction performance rather than changes in output compliance, because
compliance is already near-ceiling in the baseline condition.

\subsection{Appendix D. Supplementary Bootstrap
Figure}\label{appendix-d.-supplementary-bootstrap-figure}

The figure below visualizes the bootstrap MAE distributions underlying
the significance tests reported in the main text, showing effect sizes
and uncertainty that the bold and dagger notation in the main tables
summarizes but does not display directly.

\begin{figure}[H]

{\centering \pandocbounded{\includegraphics[keepaspectratio]{../../presentations/extraction-models-pssi/images/death-counts/bootstrap_mae_combined.png}}

}

\caption{Bootstrap MAE comparisons across seq2seq and LLM model
families.}

\end{figure}%

\newpage

\section{References}\label{references}

\setlength{\parindent}{-0.2in}
\setlength{\leftskip}{0.2in}
\setlength{\parskip}{8pt}
\noindent

\phantomsection\label{refs}
\begin{CSLReferences}{1}{0}
\bibitem[\citeproctext]{ref-braun2025}
Braun, Laura, and Christian Oswald. 2025. {``Automated Information
Extraction from Text Variables in Event Datasets with Large Language
Models.''} March 23, 2025.
\url{https://doi.org/10.31235/osf.io/yxp8k_v1}.

\bibitem[\citeproctext]{ref-brown2020}
Brown, Tom B., Benjamin Mann, Nick Ryder, Melanie Subbiah, Jared Kaplan,
Prafulla Dhariwal, Arvind Neelakantan, et al. 2020. {``Language {Models}
Are {Few-Shot Learners}.''} July 22, 2020.
\url{https://doi.org/10.48550/arXiv.2005.14165}.

\bibitem[\citeproctext]{ref-buda2018}
Buda, Mateusz, Atsuto Maki, and Maciej A. Mazurowski. 2018. {``A
Systematic Study of the Class Imbalance Problem in Convolutional Neural
Networks.''} \emph{Neural Networks} 106 (October): 249--59.
\url{https://doi.org/10.1016/j.neunet.2018.07.011}.

\bibitem[\citeproctext]{ref-chung2022}
Chung, Hyung Won, Le Hou, Shayne Longpre, Barret Zoph, Yi Tay, William
Fedus, Yunxuan Li, et al. 2022. {``Scaling {Instruction-Finetuned
Language Models}.''} December 6, 2022.
\url{https://doi.org/10.48550/arXiv.2210.11416}.

\bibitem[\citeproctext]{ref-dabre2022}
Dabre, Raj, Himani Shrotriya, Anoop Kunchukuttan, Ratish Puduppully,
Mitesh Khapra, and Pratyush Kumar. 2022. {``{IndicBART}: {A Pre-trained
Model} for {Indic Natural Language Generation}.''} In \emph{Findings of
the {Association} for {Computational Linguistics}: {ACL} 2022},
1849--63. Dublin, Ireland: Association for Computational Linguistics.
\url{https://doi.org/10.18653/v1/2022.findings-acl.145}.

\bibitem[\citeproctext]{ref-dettmers2023}
Dettmers, Tim, Artidoro Pagnoni, Ari Holtzman, and Luke Zettlemoyer.
2023. {``{QLoRA}: {Efficient} Finetuning of Quantized {LLMs}.''} In
\emph{Advances in Neural Information Processing Systems}. Vol. 36.

\bibitem[\citeproctext]{ref-dubey2024}
Dubey, Abhimanyu, Abhinav Jauhri, Abhinav Pandey, et al. 2024. {``The
Llama 3 Herd of Models.''} \url{https://arxiv.org/abs/2407.21783}.

\bibitem[\citeproctext]{ref-eck2012}
Eck, Kristine. 2012. {``In Data We Trust? {A} Comparison of {UCDP GED}
and {ACLED} Conflict Events Datasets.''} \emph{Cooperation and Conflict}
47 (1): 124--41. \url{https://doi.org/10.1177/0010836711434463}.

\bibitem[\citeproctext]{ref-halterman2025}
Halterman, Andrew. 2025. {``Synthetically Generated Text for Supervised
Text Analysis.''} \emph{Political Analysis}, January, 1--14.
\url{https://doi.org/10.1017/pan.2024.31}.

\bibitem[\citeproctext]{ref-halterman2021}
Halterman, Andrew, Katherine Keith, Sheikh Sarwar, and Brendan O'Connor.
2021. {``Corpus-{Level Evaluation} for {Event QA}: {The
IndiaPoliceEvents Corpus Covering} the 2002 {Gujarat Violence}.''} In
\emph{Findings of the {Association} for {Computational Linguistics}:
{ACL-IJCNLP} 2021}, 4240--53. Online: Association for Computational
Linguistics. \url{https://doi.org/10.18653/v1/2021.findings-acl.371}.

\bibitem[\citeproctext]{ref-he2009}
He, Haibo, and Edwardo A. Garcia. 2009. {``Learning from {Imbalanced
Data}.''} \emph{IEEE Transactions on Knowledge and Data Engineering} 21
(9): 1263--84. \url{https://doi.org/10.1109/TKDE.2008.239}.

\bibitem[\citeproctext]{ref-hu2022}
Hu, Yibo, MohammadSaleh Hosseini, Erick Skorupa Parolin, Javier Osorio,
Latifur Khan, Patrick Brandt, and Vito D'Orazio. 2022. {``{ConfliBERT}:
{A Pre-trained Language Model} for {Political Conflict} and
{Violence}.''} In \emph{Proceedings of the 2022 {Conference} of the
{North American Chapter} of the {Association} for {Computational
Linguistics}: {Human Language Technologies}}, 5469--82. Seattle, United
States: Association for Computational Linguistics.
\url{https://doi.org/10.18653/v1/2022.naacl-main.400}.

\bibitem[\citeproctext]{ref-humanrightswatch2008}
Human Rights Watch. 2008. {``{`{Being Neutral Is Our Biggest Crime}'}:
{Government}, {Vigilante}, and {Naxalite Abuses} in {India}'s
{Chhattisgarh State}.''} New York: Human Rights Watch.
\href{https://www.hrw.org/report/2008/07/14/being-neutral-our-biggest-crime/government-vigi\%20lante-and-naxalite-abuses-indias}{https://www.hrw.org/report/2008/07/14/being-neutral-our-biggest-crime/government-vigi
lante-and-naxalite-abuses-indias}.

\bibitem[\citeproctext]{ref-jiang2023mistral}
Jiang, Albert Q, Alexandre Sablayrolles, Arthur Mensch, et al. 2023.
{``Mistral {7B}.''} \url{https://arxiv.org/abs/2310.06825}.

\bibitem[\citeproctext]{ref-jiang2024mixtral}
Jiang, Albert Q, Alexandre Sablayrolles, Antoine Roux, et al. 2024.
{``Mixtral of Experts.''} \url{https://arxiv.org/abs/2401.04088}.

\bibitem[\citeproctext]{ref-leetaru2013}
Leetaru, Kalev, and Philip A Schrodt. 2013. {``{GDELT}: {Global Data} on
{Events}, {Location} and {Tone},''} In. San Francisco, CA.

\bibitem[\citeproctext]{ref-northcutt2021}
Northcutt, Curtis G., Anish Athalye, and Jonas Mueller. 2021.
{``Pervasive {Label Errors} in {Test Sets Destabilize Machine Learning
Benchmarks}.''} In \emph{Advances in Neural Information Processing
Systems}. Vol. 35. \url{https://arxiv.org/abs/2103.14749}.

\bibitem[\citeproctext]{ref-openai2023}
OpenAI. 2023. {``{GPT-4} Technical Report.''} OpenAI.

\bibitem[\citeproctext]{ref-parolin2022b}
Parolin, Erick Skorupa, Yibo Hu, Latifur Khan, Patrick T. Brandt, Javier
Osorio, and Vito D'Orazio. 2022. {``Confli-{T5}: {An AutoPrompt
Pipeline} for {Conflict Related Text Augmentation}.''} In \emph{2022
{IEEE International Conference} on {Big Data} ({Big Data})}, 1906--13.
Osaka, Japan: IEEE.
\url{https://doi.org/10.1109/BigData55660.2022.10020509}.

\bibitem[\citeproctext]{ref-raffel2020}
Raffel, Colin, Noam Shazeer, Adam Roberts, Katherine Lee, Sharan Narang,
Michael Matena, Yanqi Zhou, Wei Li, and Peter J. Liu. 2020. {``Exploring
the Limits of Transfer Learning with a Unified Text-to-Text
Transformer.''} \emph{Journal of Machine Learning Research} 21 (140):
1--67.

\bibitem[\citeproctext]{ref-raleigh2010}
Raleigh, Clionadh, Andrew Linke, Håvard Hegre, and Joakim Karlsen. 2010.
{``Introducing {ACLED}: {An} Armed Conflict Location and Event
Dataset.''} \emph{Journal of Peace Research} 47 (5): 651--60.
\url{https://doi.org/10.1177/0022343310378914}.

\bibitem[\citeproctext]{ref-schrodt1994}
Schrodt, Philip A., and Deborah J. Gerner. 1994. {``Validity
{Assessment} of a {Machine-Coded Event Data Set} for the {Middle East},
1982-92.''} \emph{American Journal of Political Science} 38 (3): 825.
\url{https://doi.org/10.2307/2111609}.

\bibitem[\citeproctext]{ref-semnani2025}
Semnani, Sina J., Pingyue Zhang, Wanyue Zhai, Haozhuo Li, Ryan
Beauchamp, Trey Billing, Katayoun Kishi, Manling Li, and Monica S. Lam.
2025. {``{LEMONADE}: {A Large Multilingual Expert-Annotated Abstractive
Event Dataset} for the {Real World}.''} 2025.
\url{https://doi.org/10.48550/ARXIV.2506.00980}.

\bibitem[\citeproctext]{ref-sennrich2016}
Sennrich, Rico, Barry Haddow, and Alexandra Birch. 2016. {``Improving
{Neural Machine Translation Models} with {Monolingual Data}.''} June 3,
2016. \url{https://doi.org/10.48550/arXiv.1511.06709}.

\bibitem[\citeproctext]{ref-simon2025}
Simon, Étienne, Helene Bøsei Olsen, Ramón Carreño, Rahul Mishra, Nikolay
Arefyev, Mert Can Yilmaz, Lilja Øvrelid, and Erik Velldal. 2025.
{``Abstractive {Event Analysis} of {Armed Conflicts}: {Introducing} the
{UCDP-AEC Dataset}.''} In \emph{Proceedings of the 21st {Conference} on
{Natural Language Processing} ({KONVENS})}. Vol. 2. Workshops.

\bibitem[\citeproctext]{ref-steinert2025}
Steinert, Christoph Valentin, and Daniel Kazenwadel. 2025. {``How User
Language Affects Conflict Fatality Estimates in {ChatGPT}.''}
\emph{Journal of Peace Research} 62 (4): 1128--43.
\url{https://doi.org/10.1177/00223433241279381}.

\bibitem[\citeproctext]{ref-sundberg2013}
Sundberg, Ralph, and Erik Melander. 2013. {``Introducing the {UCDP}
Georeferenced Event Dataset.''} \emph{Journal of Peace Research} 50 (4):
523--32. \url{https://doi.org/10.1177/0022343313484347}.

\bibitem[\citeproctext]{ref-wei2023}
Wei, Jason, Xuezhi Wang, Dale Schuurmans, Maarten Bosma, Brian Ichter,
Fei Xia, Ed Chi, Quoc Le, and Denny Zhou. 2023. {``Chain-of-{Thought
Prompting Elicits Reasoning} in {Large Language Models}.''} January 10,
2023. \url{https://doi.org/10.48550/arXiv.2201.11903}.

\bibitem[\citeproctext]{ref-xue2021}
Xue, Linting, Noah Constant, Adam Roberts, Mihir Kale, Rami Al-Rfou,
Aditya Siddhant, Aditya Barua, and Colin Raffel. 2021. {``{mT5}: A
Massively Multilingual Pre-Trained Text-to-Text Transformer.''} In
\emph{Proceedings of the 2021 Conference of the North American Chapter
of the Association for Computational Linguistics: {Human} Language
Technologies}, 483--98. Association for Computational Linguistics.

\bibitem[\citeproctext]{ref-zhong2023}
Zhong, Mian, Shehzaad Dhuliawala, and Niklas Stoehr. 2023. {``Extracting
{Victim Counts} from {Text}.''} February 23, 2023.
\url{https://doi.org/10.48550/arXiv.2302.12367}.

\end{CSLReferences}




\end{document}
